begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.request_uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

do $$
declare
  has_legacy boolean;
  legacy_count bigint;
begin
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'projects'
      and column_name = 'owner_id'
  ) into has_legacy;

  if has_legacy then
    execute 'select count(*) from public.projects' into legacy_count;

    execute '
      create table if not exists public.projects_new (
        id bigint generated by default as identity primary key,
        created_at timestamptz not null default now(),
        updated_at timestamptz null,
        user_id uuid null default public.request_uid(),
        project_name text null,
        project_scope text null
      )';

    execute '
      insert into public.projects_new (created_at, updated_at, user_id, project_name, project_scope)
      select created_at, updated_at, owner_id, name, scope
      from public.projects';

    execute 'drop table public.projects cascade';
    execute 'alter table public.projects_new rename to projects';
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid not null,
  updated_at timestamptz null,
  username text null,
  full_name text null,
  avatar_url text null,
  website text null,
  constraint profiles_pkey primary key (id),
  constraint profiles_username_key unique (username),
  constraint username_length check ((char_length(username) >= 3))
);

do $$
begin
  if to_regclass('auth.users') is not null then
    begin
      alter table public.profiles
        add constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade;
    exception
      when duplicate_object then null;
    end;
  end if;
end
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

do $$
begin
  if to_regclass('auth.users') is not null then
    execute 'update auth.users set role = ''authenticated'' where role is null or role = ''''';
    execute 'drop trigger if exists on_auth_user_created on auth.users';
    execute 'create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user()';
  end if;
end
$$;

create table if not exists public.projects (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  user_id uuid null default public.request_uid(),
  project_name text null,
  project_scope text null,
  constraint projects_pkey primary key (id)
);

do $$
begin
  if to_regclass('public.profiles') is not null then
    begin
      alter table public.projects
        add constraint projects_user_id_fkey foreign key (user_id) references public.profiles (id);
    exception
      when duplicate_object then null;
    end;
  end if;
end
$$;

create table if not exists public.flows (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  project_id bigint not null,
  flow_name text null,
  graph jsonb not null default '{"edges": [], "nodes": []}'::jsonb,
  constraint flows_pkey primary key (id),
  constraint flows_project_id_fkey foreign key (project_id) references public.projects (id) on delete cascade
);

create index if not exists flows_project_id_idx on public.flows using btree (project_id);

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists flows_set_updated_at on public.flows;
create trigger flows_set_updated_at
before update on public.flows
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.flows enable row level security;

do $$
begin
  create policy "Profiles: select own" on public.profiles
    for select
    to authenticated
    using (id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Profiles: insert own" on public.profiles
    for insert
    to authenticated
    with check (id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Profiles: update own" on public.profiles
    for update
    to authenticated
    using (id = public.request_uid())
    with check (id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Projects: select own" on public.projects
    for select
    to authenticated
    using (user_id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Projects: insert own" on public.projects
    for insert
    to authenticated
    with check (user_id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Projects: update own" on public.projects
    for update
    to authenticated
    using (user_id = public.request_uid())
    with check (user_id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Projects: delete own" on public.projects
    for delete
    to authenticated
    using (user_id = public.request_uid());
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Flows: select own" on public.flows
    for select
    to authenticated
    using (
      exists (
        select 1
        from public.projects p
        where p.id = flows.project_id
          and p.user_id = public.request_uid()
      )
    );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Flows: insert own" on public.flows
    for insert
    to authenticated
    with check (
      exists (
        select 1
        from public.projects p
        where p.id = flows.project_id
          and p.user_id = public.request_uid()
      )
    );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Flows: update own" on public.flows
    for update
    to authenticated
    using (
      exists (
        select 1
        from public.projects p
        where p.id = flows.project_id
          and p.user_id = public.request_uid()
      )
    )
    with check (
      exists (
        select 1
        from public.projects p
        where p.id = flows.project_id
          and p.user_id = public.request_uid()
      )
    );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create policy "Flows: delete own" on public.flows
    for delete
    to authenticated
    using (
      exists (
        select 1
        from public.projects p
        where p.id = flows.project_id
          and p.user_id = public.request_uid()
      )
    );
exception
  when duplicate_object then null;
end
$$;

commit;
