begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  email text not null unique,
  password_hash text not null,
  is_admin boolean not null default false
);

create index if not exists users_email_idx on public.users (email);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  user_id uuid not null references public.users (id) on delete cascade,
  token_hash text not null unique
);

create index if not exists sessions_user_id_idx on public.sessions (user_id);
create index if not exists sessions_expires_at_idx on public.sessions (expires_at);

create table if not exists public.projects (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  user_id uuid not null references public.users (id) on delete cascade,
  project_name text null,
  project_scope text null,
  constraint projects_pkey primary key (id)
);

create index if not exists projects_user_id_idx on public.projects using btree (user_id);

create table if not exists public.flows (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  project_id bigint not null references public.projects (id) on delete cascade,
  flow_name text null,
  graph jsonb not null default '{"edges": [], "nodes": []}'::jsonb,
  constraint flows_pkey primary key (id)
);

create index if not exists flows_project_id_idx on public.flows using btree (project_id);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists flows_set_updated_at on public.flows;
create trigger flows_set_updated_at
before update on public.flows
for each row
execute function public.set_updated_at();

commit;
